name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: latest
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm recursive ci
      - name: Install chromium for playwright
        run: pnpm exec playwright install chromium
      - name: Run CI
        run: pnpm run ci
      - name: Run benchmark
        run: pnpm run bench
      - name: Upload coverage results
        continue-on-error: true
        uses: coverallsapp/github-action@v2
        with:
          file: ./coverage/clover.xml
